const fs = require('fs');
const filePath = 'e:/pjei_portfolios/frontend/src/context/LanguageContext.tsx';
let content = fs.readFileSync(filePath, 'utf-8');

const laoContent = `lo: {
            title: "UknowTechno - ຜູ້ພັດທະນາດິຈິຕອລ",
            menuToggleAria: "ສະຫຼັບເມນູ",
            navAbout: "ກ່ຽວກັບ",
            navSkills: "ທັກສະ",
            navExperience: "ປະສົບການ",
            navEducation: "ການສຶກສາ",
            navProjects: "ໂຄງການ",
            navContact: "ຕິດຕໍ່",
            navAboutAria: "ໄປທີ່ພາກກ່ຽວກັບ",
            navSkillsAria: "ໄປທີ່ພາກທັກສະ",
            navExperienceAria: "ໄປທີ່ພາກປະສົບການ",
            navEducationAria: "ໄປທີ່ພາກການສຶກສາ",
            navProjectsAria: "ໄປທີ່ພາກໂຄງການ",
            navContactAria: "ໄປທີ່ພາກຕິດຕໍ່",
            langToggleAria: "ປ່ຽນພາສາ",
            themeToggleAria: "ປ່ຽນຮູບແບບ",
            scrollHome: "ໜ້າຫຼັກ",
            heroTitle: "ສະບາຍດີ, ຂ້ອຍຄື ",
            heroName: "Phengsavanh",
            heroRole: "Digital Architect & Developer",
            heroDesc: "ສະຖາປະນິກດິຈິຕອລ ແລະ ນັກພັດທະນາ Full-Stack, ສ້າງແອັບພລິເຄຊັນທີ່ແຂງແກ່ນ ດ້ວຍເຕັກໂນໂລຊີທີ່ທັນສະໄໝ.",
            heroCtaPrimary: "ເບິ່ງຜົນງານ",
            heroCtaSecondary: "ດາວໂຫຼດ CV",
            heroContactAria: "ເບິ່ງຜົນງານ",
            heroResumeAria: "ດາວໂຫຼດ CV",
            floatTopTitle: "ກັບຄືນເທິງ",
            floatTopAria: "ກັບຄືນເທິງ",
            floatBottomTitle: "ໄປລຸ່ມສຸດ",
            floatBottomAria: "ໄປລຸ່ມສຸດ",
            floatWhatsAppTitle: "ຕິດຕໍ່ WhatsApp",
            floatWhatsAppAria: "ຕິດຕໍ່ WhatsApp",
            aboutHeader: "ຂໍ້ມູນເບື້ອງຕົ້ນ",
            aboutText1: "ຂ້ອຍແມ່ນນັກພັດທະນາ Full-Stack ທີ່ມັກສ້າງລະບົບທີ່ມີປະສິດທິພາບສູງ ແລະ ສາມາດຂະຫຍາຍໄດ້.",
            aboutText2: "ດ້ວຍປະສົບການໃນການອອກແບບສະຖາປັດຕະຍະກຳຊອບແວ ແລະ ຄວາມປອດໄພຂອງຂໍ້ມູນ.",
            aboutDetailsTitle: "ຂໍ້ມູນສ່ວນຕົວ",
            aboutNameLabel: "ຊື່:",
            aboutNameValue: "Phengsavanh Phanthavong",
            aboutRoleLabel: "ໜ້າທີ່:",
            aboutRoleValue: "ນັກພັດທະນາ Full-Stack",
            aboutEmailLabel: "ອີເມວ:",
            aboutEmailValue: "contact@uknowtechno.com",
            aboutLocationLabel: "ທີ່ຢູ່:",
            aboutLocationValue: "ນະຄອນຫຼວງວຽງຈັນ, ລາວ",
            aboutLangTitle: "ພາສາ",
            aboutLangLao: "ລາວ",
            aboutLangLaoLevel: "ເຈົ້າຂອງພາສາ",
            aboutLangThai: "ໄທ",
            aboutLangThaiLevel: "ດີຫຼາຍ",
            aboutLangEnglish: "ອັງກິດ",
            aboutLangEnglishLevel: "ຂັ້ນສູງ",
            categoryLanguages: "ພາສາການຂຽນໂປຣແກຣມ",
            categoryFrameworks: "ເຟຣມເວີກ ແລະ ໄລບຣາຣີ",
            categoryAI: "AI ແລະ ການວິເຄາະຂໍ້ມູນ",
            categoryDB: "ຖານຂໍ້ມູນ ແລະ ຄລາວ",
            categoryTools: "ເຄື່ອງມື ແລະ DevOps",
            langJava: "Java",
            langPython: "Python",
            langJavaScript: "JavaScript",
            langKotlin: "Kotlin",
            langDart: "Dart",
            langCSharp: "C#",
            langHTML: "HTML",
            langCSS: "CSS",
            frameworkReact: "React",
            frameworkReactNative: "React Native",
            frameworkNode: "Node.js",
            frameworkFlutter: "Flutter",
            frameworkSpringBoot: "Spring Boot",
            frameworkDjango: "Django",
            frameworkASPNET: "ASP.NET",
            aiMachineLearning: "Machine Learning",
            aiDeepLearning: "Deep Learning",
            aiPandas: "Pandas",
            aiNumPy: "NumPy",
            aiScikit: "Scikit-learn",
            aiTensorFlow: "TensorFlow",
            dbPostgreSQL: "PostgreSQL",
            dbMongoDB: "MongoDB",
            dbFirebase: "Firebase",
            dbMySQL: "MySQL",
            dbAWS: "AWS",
            dbAzure: "Azure",
            toolDocker: "Docker",
            toolGit: "Git",
            toolAndroidStudio: "Android Studio",
            toolVSCode: "VS Code",
            toolPostman: "Postman",
            toolCICD: "CI/CD",
            blueprintHeader: "ເສັ້ນທາງອາຊີບ",
            job1Title: "ຫົວໜ້າພະແນກດິຈິຕອລແອັບພລິເຄຊັນ",
            job1Company: "PSVB Bank",
            job1Date: "ມິນາ 2023 - ປັດຈຸບັນ",
            job1Desc: "ນໍາພາການພັດທະນາ ແລະ ທົດສອບລະບົບທະນາຄານມືຖື ແລະ ອອນລາຍ.",
            job2Title: "ພະນັກງານພັດທະນາຜະລິດຕະພັນ",
            job2Company: "KokKok Solution",
            job2Date: "ຕຸລາ 2023 - ມິນາ 2023",
            job2Desc: "ສະໜັບສະໜູນການພັດທະນາຜະລິດຕະພັນໃໝ່ ຜ່ານການຄົ້ນຄວ້າດ້ານເຕັກນິກ.",
            job3Title: "ຜູ້ຊ່ຽວຊານກວດສອບພາຍໃນ",
            job3Company: "ACLEDA Bank",
            job3Date: "ມັງກອນ 2014 - ຕຸລາ 2023",
            job3Desc: "ຊ່ຽວຊານດ້ານຄວາມປອດໄພຂອງຂໍ້ມູນ ແລະ ທະນາຄານດິຈິຕອລ.",
            certHeader: "ໃບຢັ້ງຢືນ ແລະ ການຮຽນຮູ້",
            cert1Title: "ການພັດທະນາແອັບ Android",
            cert1Date: "ກໍລະກົດ - ສິງຫາ 2024",
            cert1Desc: "ສໍາເລັດການຝຶກອົບຮົມການພັດທະນາແອັບ Android ດ້ວຍ Kotlin.",
            cert2Title: "ການພັດທະນາເວັບ Full-Stack",
            cert2Date: "ມິນາ - ເມສາ 2024",
            cert2Desc: "ຊ່ຽວຊານການພັດທະນາເວັບດ້ວຍ React, Node.js, ແລະ MongoDB.",
            cert3Title: "AWS Certified Solutions Architect",
            cert3Date: "ມັງກອນ - ກຸມພາ 2024",
            cert3Desc: "ໄດ້ຮັບໃບຢັ້ງຢືນ AWS ສໍາລັບການອອກແບບລະບົບເທິງຄລາວ.",
            projectsHeader: "ໂຄງການ",
            project1Title: "ແອັບມືຖື",
            project1Desc: "ພັດທະນາແອັບມືຖືທີ່ປອດໄພດ້ວຍ Flutter ແລະ Firebase.",
            project1Image: "Mobile App",
            project2Title: "ແພລດຟອມອີຄອມເມີຊ",
            project2Desc: "ສ້າງແພລດຟອມອີຄອມເມີຊແບບ Full-Stack ດ້ວຍ React.",
            project2Image: "E-Commerce Platform",
            project3Title: "ແຊັດບອດ AI",
            project3Desc: "ອອກແບບແຊັດບອດ AI ໂດຍໃຊ້ TensorFlow ແລະ Python.",
            project3Image: "AI-Powered Chatbot",
            projectLinkCode: "ເບິ່ງໂຄດ",
            projectLinkDemo: "ເບິ່ງຕົວຈິງ",
            architectureHeader: "ສະຖາປັດຕະຍະກຳ",
            architectureTechTitle: "ວິທີການທາງເຕັກນິກ",
            architectureTechDesc: "ຜົນງານນີ້ສ້າງຂຶ້ນໂດຍເນັ້ນໃສ່ປະສິດທິພາບ ແລະ ຄວາມສວຍງາມ.",
            architectureFeaturesTitle: "ຄຸນສົມບັດຫຼັກ",
            featureResponsive: "ຮອງຮັບທຸກໜ້າຈໍ",
            featureGlassmorphism: "Glassmorphism UI",
            feature3D: "ເອັບເຟັກ 3 ມິຕິ",
            featureLanguage: "ປ່ຽນພາສາ (EN/LO)",
            featureSEO: "ຮອງຮັບ SEO",
            contactHeader: "ຕິດຕໍ່",
            contactText: "ສົນໃຈຮ່ວມງານ ຫຼື ມີໂຄງການໃນໃຈ? ຕິດຕໍ່ຫາຂ້ອຍໄດ້ເລີຍ!",
            contactEmail: "ສົ່ງຂໍ້ຄວາມ",
            contactGitHubAria: "ໂປຣໄຟລ໌ GitHub",
            contactLinkedInAria: "ໂປຣໄຟລ໌ LinkedIn",
            contactWhatsAppAria: "ຕິດຕໍ່ WhatsApp",
            footerAboutTitle: "ກ່ຽວກັບ UknowTechno",
            footerAboutText: "UknowTechno ແມ່ນນາມແຝງຂອງ Phengsavanh Phanthavong.",
            footerLinksTitle: "ລິ້ງດ່ວນ",
            footerConnectTitle: "ເຊື່ອມຕໍ່",
            footerCopyright: "© 2025 UknowTechno. ສະຫງວນລິຂະສິດ.",
            eduHeader: "ປະຫວັດການສຶກສາ",
            edu1Title: "ປະລິນຍາໂທ ວິທະຍາສາດຄອມພິວເຕີ",
            edu1Date: "ມັງກອນ 2023 - ປັດຈຸບັນ",
            edu1Desc: "ຄະນະວິທະຍາສາດທໍາມະຊາດ, ມະຫາວິທະຍາໄລແຫ່ງຊາດລາວ",
            edu2Title: "ປະລິນຍາຕີ ພາສາອັງກິດ",
            edu2Date: "2009 - 2014",
            edu2Desc: "ຄະນະອັກສອນສາດ, ມະຫາວິທະຍາໄລແຫ່ງຊາດລາວ",
        }`;

content = content.replace(/lo:\s*\{[\s\S]*?\}(?=\s*\n\s*\};)/, laoContent);
fs.writeFileSync(filePath, content, 'utf-8');
console.log('Done!');
