import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'lo';

const translations = {
  en: {
    title: "UknowTechno - Digital Architect",
    menuToggleAria: "Toggle navigation menu",
    navAbout: "About",
    navSkills: "Skills",
    navExperience: "Experience",
    navEducation: "Education",
    navProjects: "Projects",
    navContact: "Contact",
    navAboutAria: "Go to About section",
    navSkillsAria: "Go to Skills section",
    navExperienceAria: "Go to Experience section",
    navEducationAria: "Go to Education section",
    navProjectsAria: "Go to Projects section",
    navContactAria: "Go to Contact section",
    langToggleAria: "Toggle language",
    themeToggleAria: "Toggle theme",
    scrollHome: "Home",
    scrollAbout: "About",
    scrollSkills: "Skills",
    scrollExperience: "Experience",
    scrollEducation: "Education",
    scrollProjects: "Projects",
    scrollPortfolio: "Portfolio",
    scrollContact: "Contact",
    floatTopTitle: "Go to Top",
    floatBottomTitle: "Go to Bottom",
    floatWhatsAppTitle: "WhatsApp",
    floatTopAria: "Go to top of page",
    floatBottomAria: "Go to bottom of page",
    floatWhatsAppAria: "Contact via WhatsApp",
    heroFallback: "3D effect not available. Enjoy the portfolio!",
    heroName: "Phengsavanh PHANTHAVONG",
    heroTagline: "Digital Architect | Full-Stack Developer | Building Secure & Intelligent Solutions for the AI Era",
    heroCta: "Explore the Blueprint",
    heroCtaAria: "Explore the About section",
    synopsisHeader: "Synopsis: From Financial Systems to Digital Frontiers",
    profileTitle: "Personal Profile",
    profileText: "I have more than 14 years of experience in the banking industry, supported by a Master's degree in Computer Science and a strong background in modern software development. My experience spans financial systems auditing, software engineering, and full-stack development, providing me with a solid understanding of security, scalability, and business processes. Beyond my professional role, I enjoy building applications, websites, and developer tools, while studying cybersecurity and AI to continuously expand my skills. I am driven by curiosity, continuous learning, and the opportunity to apply technology to solve real-world business challenges.",
    interestsTitle: "Personal Interests",
    interestTech: "Learning Tech",
    interestFootball: "Foot ball",
    interestAdventure: "Adventure",
    interestBadminton: "Bad minton",
    languagesTitle: "Languages Spoken",
    langLao: "Lao",
    langThai: "Thai",
    langEnglish: "English",
    proficiencyNative: "Native",
    proficiencyFluent: "Fluent",
    proficiencyAdvanced: "Advanced",
    arsenalHeader: "The Arsenal: My Technology Stack",
    categoryLanguages: "Programming Languages",
    categoryFrameworks: "Frameworks & Libraries",
    categoryAI: "AI & Machine Learning",
    categoryDatabases: "Databases & Cloud",
    categoryTools: "Tools & DevOps",
    langJava: "Java",
    langPython: "Python",
    langJavaScript: "JavaScript",
    langKotlin: "Kotlin",
    langDart: "Dart",
    langCSharp: "C#",
    langHTML: "HTML",
    langCSS: "CSS",
    frameworkReact: "React",
    frameworkReactNative: "React Native",
    frameworkNode: "Node.js",
    frameworkFlutter: "Flutter",
    frameworkSpringBoot: "Spring Boot",
    frameworkDjango: "Django",
    frameworkASPNET: "ASP.NET",
    aiMachineLearning: "Machine Learning",
    aiDeepLearning: "Deep Learning",
    aiPandas: "Pandas",
    aiNumPy: "NumPy",
    aiScikit: "Scikit-learn",
    aiTensorFlow: "TensorFlow",
    dbPostgreSQL: "PostgreSQL",
    dbMongoDB: "MongoDB",
    dbFirebase: "Firebase",
    dbMySQL: "MySQL",
    dbAWS: "AWS",
    dbAzure: "Azure",
    toolDocker: "Docker",
    toolGit: "Git",
    toolAndroidStudio: "Android Studio",
    toolVSCode: "VS Code",
    toolPostman: "Postman",
    toolCICD: "CI/CD",
    frameworkAntigravity: "Antigravity",
    frameworkCloudCode: "Claude Code",
    frameworkNextJS: "Next.js",
    frameworkTailwind: "Tailwind CSS",
    aiMoE: "MoE",
    aiRAG: "RAG",
    aiLLMs: "LLMs",
    aiLangChain: "LangChain",
    aiPyTorch: "PyTorch",
    dbSupabase: "Supabase",
    dbCloudflare: "Cloudflare",
    dbVercel: "Vercel",
    dbRedis: "Redis",
    toolKubernetes: "Kubernetes",
    toolGitHubActions: "GitHub Actions",
    toolTerraform: "Terraform",
    toolFigma: "Figma",
    langTypeScript: "TypeScript",
    langGo: "Go",
    langRust: "Rust",
    langSwift: "Swift",
    langPHP: "PHP",
    langRuby: "Ruby",
    langCPP: "C++",
    langSQL: "SQL",
    frameworkVue: "Vue.js",
    frameworkAngular: "Angular",
    frameworkSvelte: "Svelte",
    frameworkExpress: "Express.js",
    frameworkFastAPI: "FastAPI",
    aiOpenAI: "OpenAI",
    aiHuggingFace: "Hugging Face",
    aiKeras: "Keras",
    aiOpenCV: "OpenCV",
    aiMLOps: "MLOps",
    dbGCP: "Google Cloud",
    dbOracle: "Oracle",
    dbSQLite: "SQLite",
    dbCassandra: "Cassandra",
    dbElasticSearch: "ElasticSearch",
    dbSnowflake: "Snowflake",
    toolJenkins: "Jenkins",
    toolLinux: "Linux",
    toolJira: "Jira",
    toolWebpack: "Webpack",
    toolVite: "Vite",
    toolSlack: "Slack",
    blueprintHeader: "The Blueprint: Career Trajectory",
    job1Title: "Head of Digital Application Division",
    job1Company: "PSVB Bank",
    job1Date: "Mar 2023 - Present",
    job1Desc: "Leading the development, system integration, and pre-launch testing of mobile and online banking platforms. Collaborating with cross-functional teams to deliver secure, reliable, and high-quality digital financial services while ensuring compliance with business and technical requirements.",
    job2Title: "Product Development Staff",
    job2Company: "KokKok Solution",
    job2Date: "Oct 2023 - Mar 2023",
    job2Desc: "Supported the development of new digital products by conducting technical research, validating solutions, and performing comprehensive pre-launch testing for new features and releases. Helped ensure system stability, optimal performance, and a seamless user experience before production deployment.",
    job3Title: "Internal Auditor Specialist",
    job3Company: "ACLEDA Bank",
    job3Date: "Jan 2014 - Oct 2023",
    job3Desc: "Specialized in Information Security, Digital Banking, and AML/CFT. Served as Branch Internal Audit Manager, leading comprehensive audits of financial products and branch operations across the Vientiane and Chanthabuly branches while ensuring compliance with internal policies and regulatory requirements.",
    certHeader: "Skill Accreditations & Continuous Learning",
    cert1Title: "Android App Development",
    cert1Date: "Jul 23 - Aug 2, 2024",
    cert1Desc: "Completed intensive training in Android application development, gaining hands-on experience with Kotlin and Android Studio while building responsive, user-friendly mobile applications and applying mobile development best practices.",
    cert2Title: "Advanced Programming Training",
    cert2Date: "Dec 05-Dec 09 2023",
    cert2Desc: "Completed advanced training in Python programming, focusing on sensor integration, hardware control, and automation. Developed practical experience in interfacing with sensor kits, processing real-time data, and building applications for monitoring and control systems.",
    cert3Title: "Java Programming Training",
    cert3Date: "Jul 14 - Aug 25, 2023",
    cert3Desc: "Completed comprehensive training in Java application development, with a focus on building web applications using Spring MVC, Hibernate, MySQL, and RESTful APIs. Gained hands-on experience in designing and developing CRUD applications, implementing database integration, and applying object-oriented programming principles and industry best practices.",
    projectsHeader: "Project Showcase",
    project1Title: "Mobile App",
    project1Desc: "Developed secure cross-platform mobile applications using Flutter and Supabase, integrating modern technologies such as AI, authentication, cloud databases, and RESTful APIs. Personal projects include **Lao QR Parser + AI**, **OmniKit (All-in-One Tools + AI)**, **Smart HR + AI**, and other applications focused on improving productivity and solving real-world problems.",
    project1Image: "Mobile App",
    project2Title: "Website",
    project2Desc: "Designed and developed full-stack web applications using React, Node.js, and MongoDB, including banking document management systems, task management platforms, e-commerce solutions, and other business applications. Focused on scalable architecture, secure data management, RESTful APIs, and responsive user experiences.",
    project2Image: "E-Commerce Platform",
    project3Title: "AI-Powered Chatbot",
    project3Desc: "Designed an AI-powered chatbot using TensorFlow and Python, integrated with customer service platforms to automate responses.",
    project3Image: "AI-Powered Chatbot",
    projectLinkCode: "View Code",
    projectLinkDemo: "Live Demo",
    architectureHeader: "Portfolio Architecture",
    architectureTechTitle: "Technical Approach",
    architectureTechDesc: "This portfolio is built with a focus on performance, accessibility, and visual appeal. Leveraging HTML5, CSS3, and JavaScript with Three.js for 3D effects, it features a responsive design, glassmorphism aesthetics, and dynamic animations. The site is optimized for SEO and includes a custom language toggle for English and Thai, ensuring inclusivity.",
    architectureFeaturesTitle: "Key Features",
    featureResponsive: "Responsive Design",
    featureGlassmorphism: "Glassmorphism UI",
    feature3D: "3D Visual Effects",
    featureLanguage: "Language Toggle (EN/TH)",
    featureSEO: "SEO Optimized",
    contactHeader: "Get in Touch",
    contactText: "Interested in collaborating or have a project in mind? I'd be happy to connect and explore how we can build secure, innovative, and impactful solutions together!",
    contactEmail: "Send a Message",
    contactGitHubAria: "GitHub Profile",
    contactLinkedInAria: "LinkedIn Profile",
    contactWhatsAppAria: "WhatsApp Contact",
    footerAboutTitle: "What does UknowTechno mean?",
    footerAboutText: "UknowTechno reflects the belief that anyone can understand technology through continuous learning and curiosity. Technology never stands still—it evolves every day. By embracing lifelong learning, research, and hands-on practice, we can grow alongside innovation and stay ready for the challenges of tomorrow.",
    footerTagline: "Apps and websites built end-to-end — from idea to production.",
    footerProductsTitle: "Products",
    footerLinksTitle: "Quick Links",
    footerConnectTitle: "Connect",
    footerCopyright: "© 2025 UknowTechno. All rights reserved.",
    eduHeader: "Educational Foundation",
    edu1Title: "Master in Computer Science",
    edu1Date: "Jan 2023 - Jan 2026",
    edu1Desc: "Faculty of Natural Sciences, National University of Laos",
    edu2Title: "Bachelor's in English",
    edu2Date: "2009 - 2014",
    edu2Desc: "Faculty of Education, National University of Laos",
    projectsTitle: "Project Showcase",
    interestSports: "Sports",
    chatNewChat: "New Chat",
    chatRecent: "Recent",
    chatToggleSidebar: "Toggle Sidebar",
    chatAIEngine: "UKnowTechno AI",
    chatGreeting: "How can I help you today?",
    chatGreetingSub: "I'm a powerful AI assistant powered by advanced LLMs.",
    chatInputPlaceholder: "Message AI or paste an image...",
    chatAttachFile: "Attach file or image",
    chatUseMic: "Use microphone",
    chatDisclaimer: "AI can make mistakes. Verify important information.",
    chatOffline: "*AI Engine Offline for Maintenance.*",
    chatTimeout: "*The AI engine took too long to respond. It may be offline — please try again shortly.*",
    chatRateLimited: "*You're sending messages too quickly. Please wait a moment and try again.*",
    chatSmartOn: "Smart mode ON — using the advanced cloud model",
    chatSmartOff: "Smart mode — tap to use the advanced model for hard questions",
    chatListening: "🎤 Listening...",
    adminSystemAdmin: "ADMIN SYSTEM",
    adminSecureId: "SECURE ID",
    adminPassphrase: "PASSPHRASE",
    adminInitConnection: "INITIALIZE CONNECTION",
    adminDashboard: "DASHBOARD",
    adminAiModels: "AI MODELS",
    adminKnowledge: "KNOWLEDGE (RAG)",
    adminSignOut: "SIGN OUT",
    adminSystemOverview: "SYSTEM OVERVIEW",
    adminOnline: "Online",
    adminPocketbaseStatus: "POCKETBASE STATUS",
    adminChunks: "Chunks",
    adminVectorsQdrant: "VECTORS IN QDRANT",
    adminActiveLlmRoute: "ACTIVE LLM ROUTE",
    adminAiRouting: "AI ROUTING & BUDGETING",
    adminActiveFree: "ACTIVE (FREE)",
    adminRouteTarget: "ROUTE TARGET",
    adminTotalUsage: "TOTAL USAGE (UNLIMITED)",
    adminTokensGenerated: "TOKENS GENERATED",
    adminMonthlyBudgetLimit: "MONTHLY BUDGET LIMIT ($)",
    adminCurrentSpend: "CURRENT SPEND",
    adminKnowledgeBase: "KNOWLEDGE BASE (RAG)",
    adminSemanticChunking: "SEMANTIC CHUNKING & DB MANAGEMENT",
    adminSmartUpload: "SMART UPLOAD",
    adminAutoPipeline: "AUTOMATED SEMANTIC PIPELINE",
    adminUploading: "1. UPLOADING SECURE DOCUMENT...",
    adminAnalyzing: "2. ANALYZING DOCUMENT HIERARCHY...",
    adminApplying: "3. APPLYING SEMANTIC CHUNKING (SPLITTING UNITS)...",
    adminComputing: "4. COMPUTING VECTOR EMBEDDINGS...",
    adminEditChunk: "EDIT HIERARCHICAL CHUNK",
    adminFileName: "FILE NAME",
    adminUnitTopic: "UNIT / MAIN TOPIC",
    adminSubTopic: "SUB-TOPIC / SECTION",
    adminVectorContent: "VECTOR CONTENT (PAYLOAD)",
    adminCancel: "CANCEL",
    adminCommit: "COMMIT TO .DB",
    adminSearch: "Search database contents or topics...",
    adminHierarchy: "Hierarchy (File > Topic)",
    adminVectorPayload: "Vector Payload",
    adminActions: "Actions",
    adminManual: "MANUAL",
    adminPurge: "PURGE",
    adminNoData: "NO SEMANTIC DATA FOUND",
    adminUploadDoc: "Upload a document to automatically populate the vector database.",

    // --- Business Home (v2) ---
    navHome: "Home",
    navApps: "Apps",
    navServices: "Services",
    navConnect: "Connect",
    navAboutMe: "About Me",
    navHomeAria: "Go to Home",
    navAppsAria: "Go to Apps section",
    navServicesAria: "Go to Services section",
    navConnectAria: "Go to Connect section",
    navAboutMeAria: "Go to About Me page",
    scrollApps: "Apps",
    scrollServices: "Services",
    scrollStack: "Stack",
    scrollConnect: "Connect",

    bizHeroEyebrow: "Full-Stack Developer · Android & Web",
    bizHeroHeadline: "I build apps and websites",
    bizHeroHighlight: "people actually use.",
    bizHeroSub: "14+ years in banking & software, now shipping Android apps and modern web products end-to-end — from idea to Play Store to production.",
    bizHeroCtaApps: "See My Apps",
    bizHeroCtaHire: "Discuss Your Project",
    bizHeroStatYears: "14+ Years Experience",
    bizHeroStatApps: "4 Apps Built",
    bizHeroStatStack: "Full-Stack: Mobile · Web · Backend",

    appsHeader: "Apps I've Built",
    appsSub: "Live on the Play Store, in beta, or actively in development — real products, not just demos.",
    statusLive: "Live on Play Store",
    statusBeta: "Beta / Testing",
    statusDev: "In Development",
    appCtaInstall: "View on Play Store",
    appCtaSoon: "Coming Soon",

    app1Title: "Lao QR Parse: Pay & Budget",
    app1Desc: "Parses Lao QR payment codes and turns every scan into automatic budget tracking — see where your money goes without manual entry.",
    app2Title: "OmniKit – Toolkit",
    app2Desc: "An all-in-one Android toolkit bundling the everyday utilities people reach for constantly, in one clean, ad-light app.",
    app3Title: "Smart HR: Attendance & Leave",
    app3Desc: "Attendance tracking and leave management for small teams — clock in/out, leave requests, and approvals in one simple flow.",
    app4Title: "LinkZap: Easy Food",
    app4Desc: "A fast, simple food ordering experience, currently in active development. Follow the socials below for the launch.",

    servicesHeader: "What I Can Build For You",
    servicesSub: "End-to-end development — I design, build, test, and ship it, not just prototype it.",
    service1Title: "Mobile Apps",
    service1Desc: "Native Android (Kotlin) and cross-platform (Flutter, React Native, MAUI) apps — from concept to a published, maintained Play Store listing.",
    service2Title: "Websites & Web Apps",
    service2Desc: "Fast, responsive sites and full web applications with React, TypeScript, Tailwind, Vue, and Next.js — built for real users, not just Lighthouse scores.",
    service3Title: "Backend & APIs",
    service3Desc: "Secure REST APIs and cloud infrastructure with Node.js, Supabase, Firebase, and Cloudflare — built to scale with your product.",
    servicesPricingTitle: "Pricing that makes sense",
    servicesPricingText: "Individuals and small projects: free. Bigger or commercial projects: let's discuss scope and budget first — no surprise costs.",
    servicesCta: "Tell Me About Your Project",
    service4Title: "Windows Apps & Tools",
    service4Desc: "Desktop utilities and internal tools for Windows — built with .NET/C#, Python, and Java.",
    service5Title: "AI Models & Research",
    service5Desc: "Applied AI: RAG pipelines, local & cloud LLM routing, fine-tuning experiments, and research prototypes that go beyond a chatbot wrapper.",
    service6Title: "Database & Server",
    service6Desc: "Data layer and infrastructure: PostgreSQL, MongoDB, and MySQL, plus Linux server administration and Docker containerization.",

    stackHeader: "Tools & Stack I Work With",
    stackSub: "The languages, frameworks, and infrastructure behind everything I ship.",
    stackCtaText: "Want the full list? See the complete tech arsenal on my About page.",
    stackCtaLink: "View Full Stack →",

    connectHeader: "Follow Along & Get In Touch",
    connectSub: "New builds, dev logs, and releases — before they hit the Play Store.",
    connectYouTubeDesc: "Dev logs, app walkthroughs & build-in-public videos",
    connectGitHubDesc: "Open-source code, experiments & side projects",
    connectFacebookDesc: "Updates, announcements & behind-the-scenes",
    connectPlayStoreDesc: "All published apps in one place",
    connectFacebookAria: "Facebook Page",
    connectTikTokDesc: "Short-form dev clips, app demos & behind-the-scenes",
    connectTikTokAria: "TikTok Profile",

    homeAboutTeaser: "Want the full story — 14 years in banking, a Master's in Computer Science, and how I got here?",
    homeAboutTeaserCta: "Read My Full Story →"
  },
  lo: {
    title: "UknowTechno - ຜູ້ພັດທະນາດິຈິຕອລ",
    arsenalHeader: "ຄັງເຕັກໂນໂລຢີຂອງຂ້ອຍ",
    menuToggleAria: "ສະຫຼັບເມນູ",
    navAbout: "ກ່ຽວກັບ",
    navSkills: "ທັກສະ",
    navExperience: "ປະສົບການ",
    navEducation: "ການສຶກສາ",
    navProjects: "ໂຄງການ",
    navContact: "ຕິດຕໍ່",
    navAboutAria: "ໄປທີ່ພາກກ່ຽວກັບ",
    navSkillsAria: "ໄປທີ່ພາກທັກສະ",
    navExperienceAria: "ໄປທີ່ພາກປະສົບການ",
    navEducationAria: "ໄປທີ່ພາກການສຶກສາ",
    navProjectsAria: "ໄປທີ່ພາກໂຄງການ",
    navContactAria: "ໄປທີ່ພາກຕິດຕໍ່",
    langToggleAria: "ປ່ຽນພາສາ",
    themeToggleAria: "ປ່ຽນຮູບແບບ",
    scrollHome: "ໜ້າຫຼັກ",
    scrollAbout: "ກ່ຽວກັບ",
    scrollSkills: "ທັກສະ",
    scrollExperience: "ປະສົບການ",
    scrollEducation: "ການສຶກສາ",
    scrollProjects: "ໂຄງການ",
    scrollPortfolio: "ຜົນງານ",
    scrollContact: "ຕິດຕໍ່",
    synopsisHeader: "ເລື່ອງຫຍໍ້: ຈາກລະບົບການເງິນສູ່ໂລກດິຈິຕອນ",
    heroTagline: "ນັກອອກແບບສະຖາປັດຕະຍະກຳດິຈິຕອນ | ນັກພັດທະນາ Full-Stack | ສ້າງສັນໂຊລູຊັນທີ່ປອດໄພ ແລະ ຊົງປັນຍາ ສຳລັບຍຸກ AI",
    heroTitle: "ສະບາຍດີ, ຂ້ອຍຄື ",
    heroName: "ເພັງສະຫວັນ ພັນທະວົງ",
    heroFallback: "Phengsavanh",
    heroRole: "Digital Architect & Developer",
    heroDesc: "ສະຖາປະນິກດິຈິຕອລ ແລະ ນັກພັດທະນາ Full-Stack, ສ້າງແອັບພລິເຄຊັນທີ່ແຂງແກ່ນ ດ້ວຍເຕັກໂນໂລຊີທີ່ທັນສະໄໝ.",
    heroCta: "ສຳຫຼວດພິມຂຽວ",
    heroCtaPrimary: "ເບິ່ງຜົນງານ",
    heroCtaSecondary: "ດາວໂຫຼດ CV",
    heroContactAria: "ເບິ່ງຜົນງານ",
    heroResumeAria: "ດາວໂຫຼດ CV",
    floatTopTitle: "ກັບຄືນເທິງ",
    floatTopAria: "ກັບຄືນເທິງ",
    floatBottomTitle: "ໄປລຸ່ມສຸດ",
    floatBottomAria: "ໄປລຸ່ມສຸດ",
    floatWhatsAppTitle: "ຕິດຕໍ່ WhatsApp",
    floatWhatsAppAria: "ຕິດຕໍ່ WhatsApp",
    aboutHeader: "ຂໍ້ມູນເບື້ອງຕົ້ນ",
    aboutText1: "ຂ້ອຍແມ່ນນັກພັດທະນາ Full-Stack ທີ່ມັກສ້າງລະບົບທີ່ມີປະສິດທິພາບສູງ ແລະ ສາມາດຂະຫຍາຍໄດ້.",
    aboutText2: "ດ້ວຍປະສົບການໃນການອອກແບບສະຖາປັດຕະຍະກຳຊອບແວ ແລະ ຄວາມປອດໄພຂອງຂໍ້ມູນ.",
    aboutDetailsTitle: "ຂໍ້ມູນສ່ວນຕົວ",
    aboutNameLabel: "ຊື່:",
    aboutNameValue: "ເພັງສະຫວັນ ພັນທະວົງ",
    aboutRoleLabel: "ໜ້າທີ່:",
    aboutRoleValue: "ນັກພັດທະນາ Full-Stack",
    aboutEmailLabel: "ອີເມວ:",
    aboutEmailValue: "contact@uknowtechno.com",
    aboutLocationLabel: "ທີ່ຢູ່:",
    aboutLocationValue: "ນະຄອນຫຼວງວຽງຈັນ, ລາວ",
    aboutLangTitle: "ພາສາ",
    aboutLangLao: "ລາວ",
    aboutLangLaoLevel: "ເຈົ້າຂອງພາສາ",
    aboutLangThai: "ໄທ",
    aboutLangThaiLevel: "ດີຫຼາຍ",
    aboutLangEnglish: "ອັງກິດ",
    aboutLangEnglishLevel: "ຂັ້ນສູງ",
    categoryLanguages: "ພາສາການຂຽນໂປຣແກຣມ",
    categoryFrameworks: "ເຟຣມເວີກ ແລະ ໄລບຣາຣີ",
    categoryAI: "AI ແລະ ການວິເຄາະຂໍ້ມູນ",
    categoryDB: "ຖານຂໍ້ມູນ ແລະ ຄລາວ",
    categoryTools: "ເຄື່ອງມື ແລະ DevOps",
    langJava: "Java",
    langPython: "Python",
    langJavaScript: "JavaScript",
    langKotlin: "Kotlin",
    langDart: "Dart",
    langCSharp: "C#",
    langHTML: "HTML",
    langCSS: "CSS",
    frameworkReact: "React",
    frameworkReactNative: "React Native",
    frameworkNode: "Node.js",
    frameworkFlutter: "Flutter",
    frameworkSpringBoot: "Spring Boot",
    frameworkDjango: "Django",
    frameworkASPNET: "ASP.NET",
    aiMachineLearning: "Machine Learning",
    aiDeepLearning: "Deep Learning",
    aiPandas: "Pandas",
    aiNumPy: "NumPy",
    aiScikit: "Scikit-learn",
    aiTensorFlow: "TensorFlow",
    dbPostgreSQL: "PostgreSQL",
    dbMongoDB: "MongoDB",
    dbFirebase: "Firebase",
    dbMySQL: "MySQL",
    dbAWS: "AWS",
    dbAzure: "Azure",
    toolDocker: "Docker",
    toolGit: "Git",
    toolAndroidStudio: "Android Studio",
    toolVSCode: "VS Code",
    toolPostman: "Postman",
    toolCICD: "CI/CD",
    frameworkAntigravity: "Antigravity",
    frameworkCloudCode: "Claude Code",
    frameworkNextJS: "Next.js",
    frameworkTailwind: "Tailwind CSS",
    aiMoE: "MoE",
    aiRAG: "RAG",
    aiLLMs: "LLMs",
    aiLangChain: "LangChain",
    aiPyTorch: "PyTorch",
    dbSupabase: "Supabase",
    dbCloudflare: "Cloudflare",
    dbVercel: "Vercel",
    dbRedis: "Redis",
    toolKubernetes: "Kubernetes",
    toolGitHubActions: "GitHub Actions",
    toolTerraform: "Terraform",
    toolFigma: "Figma",
    langTypeScript: "TypeScript",
    langGo: "Go",
    langRust: "Rust",
    langSwift: "Swift",
    langPHP: "PHP",
    langRuby: "Ruby",
    langCPP: "C++",
    langSQL: "SQL",
    frameworkVue: "Vue.js",
    frameworkAngular: "Angular",
    frameworkSvelte: "Svelte",
    frameworkExpress: "Express.js",
    frameworkFastAPI: "FastAPI",
    aiOpenAI: "OpenAI",
    aiHuggingFace: "Hugging Face",
    aiKeras: "Keras",
    aiOpenCV: "OpenCV",
    aiMLOps: "MLOps",
    dbGCP: "Google Cloud",
    dbOracle: "Oracle",
    dbSQLite: "SQLite",
    dbCassandra: "Cassandra",
    dbElasticSearch: "ElasticSearch",
    dbSnowflake: "Snowflake",
    toolJenkins: "Jenkins",
    toolLinux: "Linux",
    toolJira: "Jira",
    toolWebpack: "Webpack",
    toolVite: "Vite",
    toolSlack: "Slack",
    blueprintHeader: "ເສັ້ນທາງອາຊີບ",
    job1Title: "ຫົວໜ້າພາກສວນຝ່າຍດິຈິຕອລແອັບພລິເຄຊັນ",
    job1Company: "PSVB Bank",
    job1Date: "ມິນາ 2023 - ປັດຈຸບັນ",
    job1Desc: "ນຳພາການພັດທະນາ, ການເຊື່ອມຕໍ່ລະບົບ (System Integration) ແລະ ການທົດສອບກ່ອນເປີດໃຫ້ບໍລິການ (Pre-launch Testing) ສຳລັບລະບົບ Mobile Banking ແລະ Online Banking. ປະສານງານກັບທີມງານຂ້າມສາຍງານ (Cross-functional Teams) ເພື່ອໃຫ້ການສົ່ງມອບບໍລິການການເງິນດິຈິຕອນທີ່ມີຄວາມປອດໄພ, ເຊື່ອຖືໄດ້ ແລະ ຕອບສະໜອງຄວາມຕ້ອງການທັງດ້ານທຸລະກິດ ແລະ ເຕັກນິກ.",
    job2Title: "ພະນັກງານພັດທະນາຜະລິດຕະພັນ",
    job2Company: "KokKok Solution",
    job2Date: "ຕຸລາ 2023 - ມິນາ 2023",
    job2Desc: "ສະໜັບສະໜູນການພັດທະນາຜະລິດຕະພັນດິຈິຕອນໃໝ່ ໂດຍການຄົ້ນຄວ້າດ້ານເຕັກນິກ, ການປະເມີນ ແລະ ກວດສອບແນວທາງແກ້ໄຂ (Solution Validation), ພ້ອມທັງດຳເນີນການທົດສອບຢ່າງຄົບຖ້ວນກ່ອນການເປີດໃຫ້ບໍລິການ ສຳລັບຟັງຊັນ ແລະ ການອັບເດດລະບົບໃໝ່. ຊ່ວຍໃຫ້ລະບົບມີຄວາມສະຖຽນ, ປະສິດທິພາບສູງ ແລະ ສ້າງປະສົບການທີ່ດີໃຫ້ແກ່ຜູ້ໃຊ້ກ່ອນນຳໄປໃຊ້ງານຈິງ.",
    job3Title: "ຜູ້ຊ່ຽວຊານກວດສອບພາຍໃນ",
    job3Company: "ACLEDA Bank",
    job3Date: "ມັງກອນ 2014 - ຕຸລາ 2023",
    job3Desc: "ມີຄວາມຊ່ຽວຊານດ້ານຄວາມປອດໄພສານສະໜເທດ (Information Security), ລະບົບທະນາຄານດິຈິຕອນ (Digital Banking) ແລະ ການປ້ອງກັນ ແລະ ຕ້ານການຟອກເງິນ ແລະ ການສະໜັບສະໜູນການກໍ່ການຮ້າຍ (AML/CFT). ເຄີຍດຳລົງຕຳແໜ່ງຜູ້ຈັດການກວດສອບພາຍໃນສາຂາ (Branch Internal Audit Manager) ຮັບຜິດຊອບນຳພາການກວດສອບຜະລິດຕະພັນທາງການເງິນ ແລະ ຂະບວນການດຳເນີນງານຂອງສາຂານະຄອນຫຼວງ ແລະ ສາຂາຈັນທະບູລີ ໂດຍຮັບປະກັນຄວາມສອດຄ່ອງກັບນະໂຍບາຍພາຍໃນ ແລະ ຂໍ້ກຳນົດຂອງໜ່ວຍງານກຳກັບດູແລ.",
    certHeader: "ໃບຢັ້ງຢືນ ແລະ ການຮຽນຮູ້",
    cert1Title: "ການພັດທະນາແອັບ Android",
    cert1Date: "ກໍລະກົດ - ສິງຫາ 2024",
    cert1Desc: "ສຳເລັດຫຼັກສູດຝຶກອົບຮົມແບບເຂັ້ມຂົ້ນດ້ານການພັດທະນາແອັບພລິເຄຊັນ Android ໂດຍເນັ້ນການນຳໃຊ້ Kotlin ແລະ Android Studio. ໄດ້ພັດທະນາແອັບພລິເຄຊັນທີ່ຕອບສະໜອງໄດ້ດີ (Responsive) ແລະ ເປັນມິດກັບຜູ້ໃຊ້ (User-friendly) ພ້ອມທັງເສີມສ້າງທັກສະດ້ານການພັດທະນາ Android ຕາມແນວປະຕິບັດທີ່ດີ.",
    cert2Title: "ການຝຶກອົບຮົມການຂຽນໂປຣແກຣມຂັ້ນສູງ",
    cert2Date: "ມິນາ - ເມສາ 2024",
    cert2Desc: "ສຳເລັດຫຼັກສູດຝຶກອົບຮົມຂັ້ນສູງດ້ານການຂຽນໂປຣແກຣມດ້ວຍພາສາ Python ໂດຍເນັ້ນການເຊື່ອມຕໍ່ ແລະ ຄວບຄຸມອຸປະກອນ Sensor, ການເກັບຮວບຮວມ ແລະ ປະມວນຜົນຂໍ້ມູນແບບ Real-time ພ້ອມທັງການພັດທະນາລະບົບສຳລັບການຕິດຕາມ, ຄວບຄຸມ ແລະ ງານດ້ານ Automation.",
    cert3Title: "ການຝຶກອົບຮົມການຂຽນໂປຣແກຣມ Java",
    cert3Date: "ມັງກອນ - ກຸມພາ 2024",
    cert3Desc: "ສຳເລັດຫຼັກສູດຝຶກອົບຮົມດ້ານການພັດທະນາແອັບພລິເຄຊັນດ້ວຍພາສາ Java ໂດຍເນັ້ນການພັດທະນາເວັບແອັບພລິເຄຊັນຜ່ານ Spring MVC, Hibernate, MySQL ແລະ RESTful APIs. ໄດ້ຝຶກປະຕິບັດການອອກແບບ ແລະ ພັດທະນາລະບົບ CRUD (Create, Read, Update, Delete), ການເຊື່ອມຕໍ່ຖານຂໍ້ມູນ, ການອອກແບບຊອບແວຕາມຫຼັກ Object-Oriented Programming (OOP) ແລະ ການນຳໃຊ້ແນວປະຕິບັດທີ່ດີໃນການພັດທະນາຊອບແວ.",
    profileText: "ຂ້ອຍມີປະສົບການຫຼາຍກວ່າ 14 ປີ ໃນອຸດສາຫະກຳການທະນາຄານ ໂດຍມີວຸດທິການສຶກສາລະດັບປະລິນຍາໂທ ສາຂາວິທະຍາການຄອມພິວເຕີ (Computer Science) ແລະ ມີພື້ນຖານທີ່ແຂງແຮງດ້ານການພັດທະນາຊອບແວສະໄໝໃໝ່. ປະສົບການຂອງຂ້ອຍຄອບຄຸມຕັ້ງແຕ່ການກວດສອບລະບົບການເງິນ, ວິສະວະກຳຊອບແວ ຈົນເຖິງການພັດທະນາລະບົບແບບ Full-Stack ເຮັດໃຫ້ຂ້ອຍມີຄວາມເຂົ້າໃຈຢ່າງເລິກເຊິ່ງດ້ານຄວາມປອດໄພ (Security), ຄວາມສາມາດໃນການຮອງຮັບການເຕີບໂຕຂອງລະບົບ (Scalability) ແລະ ຂະບວນການທາງທຸລະກິດ. ນອກເໜືອຈາກໜ້າທີ່ການງານ, ຂ້ອຍມັກສ້າງແອັບພລິເຄຊັນ, ເວັບໄຊ ແລະ ເຄື່ອງມືສຳລັບນັກພັດທະນາ (Developer Tools) ພ້ອມທັງສຶກສາດ້ານ Cybersecurity ແລະ AI ເພື່ອພັດທະນາທັກສະຂອງຕົນເອງຢ່າງຕໍ່ເນື່ອງ. ຂ້ອຍເຊື່ອໃນພະລັງຂອງຄວາມຢາກຮຽນຮູ້, ການພັດທະນາຕົນເອງຢ່າງບໍ່ຢຸດຢັ້ງ ແລະ ການນຳເທັກໂນໂລຢີມາປະຍຸກຕ໌ໃຊ້ເພື່ອແກ້ໄຂບັນຫາທາງທຸລະກິດໃນໂລກຄວາມເປັນຈິງ.",
    profileTitle: "ໂປຣໄຟລ໌ສ່ວນຕົວ",
    interestsTitle: "ຄວາມສົນໃຈສ່ວນຕົວ",
    interestTech: "ການຮຽນຮູ້ເທັກໂນໂລຢີ",
    interestAdventure: "ການຜະຈົນໄພ",
    projectsHeader: "ໂຄງການ",
    project1Title: "ແອັບມືຖື",
    project1Desc: "ອອກແບບ ແລະ ພັດທະນາແອັບພລິເຄຊັນມືຖືຂ້າມແພລດຟອມ (Cross-platform) ດ້ວຍ Flutter ແລະ Supabase ໂດຍເນັ້ນຄວາມປອດໄພ, ປະສິດທິພາບ ແລະ ປະສົບການການໃຊ້ງານ. ນຳ AI, ລະບົບຢືນຢັນຕົວຕົນ (Authentication), Cloud Database ແລະ RESTful APIs ມາປະຍຸກຕ໌ໃຊ້ໃນການພັດທະນາ. ຜົນງານປະກອບມີ *Lao QR Parser + AI*, *OmniKit (ຊຸດເຄື່ອງມືອະເນກປະສົງພ້ອມ AI)*, *Smart HR + AI* ແລະ ໂຄງການອື່ນໆ ທີ່ມຸ່ງເນັ້ນການນຳເທັກໂນໂລຢີມາແກ້ໄຂບັນຫາ ແລະ ເພີ່ມປະສິດທິພາບໃນການເຮັດວຽກ.",
    project1Image: "Mobile App",
    project2Title: "ເວັບໄຊທ໌",
    project2Desc: "ອອກແບບ ແລະ ພັດທະນາລະບົບເວັບແບບ Full-Stack ໂດຍນຳໃຊ້ React, Node.js ແລະ MongoDB ສຳລັບລະບົບຈັດການເອກະສານທະນາຄານ, ລະບົບຈັດການວຽກງານ (Task Management), ແພລດຟອມ E-commerce ແລະ ລະບົບສຳລັບທຸລະກິດອື່ນໆ. ມຸ່ງເນັ້ນການອອກແບບລະບົບທີ່ຮອງຮັບການຂະຫຍາຍ (Scalable Architecture), ການຈັດການຂໍ້ມູນຢ່າງປອດໄພ, ການພັດທະນາ RESTful APIs ແລະ ປະສົບການການໃຊ້ງານທີ່ດີຜ່ານທຸກອຸປະກອນ.",
    project2Image: "E-Commerce Platform",
    project3Title: "ແຊັດບອດ AI",
    project3Desc: "ອອກແບບແຊັດບອດ AI ໂດຍໃຊ້ TensorFlow ແລະ Python.",
    project3Image: "AI-Powered Chatbot",
    projectLinkCode: "ເບິ່ງໂຄດ",
    projectLinkDemo: "ເບິ່ງຕົວຈິງ",
    architectureHeader: "ສະຖາປັດຕະຍະກຳ",
    architectureTechTitle: "ວິທີການທາງເຕັກນິກ",
    architectureTechDesc: "ຜົນງານນີ້ສ້າງຂຶ້ນໂດຍເນັ້ນໃສ່ປະສິດທິພາບ ແລະ ຄວາມສວຍງາມ.",
    architectureFeaturesTitle: "ຄຸນສົມບັດຫຼັກ",
    featureResponsive: "ຮອງຮັບທຸກໜ້າຈໍ",
    featureGlassmorphism: "Glassmorphism UI",
    feature3D: "ເອັບເຟັກ 3 ມິຕິ",
    featureLanguage: "ປ່ຽນພາສາ (EN/LO)",
    featureSEO: "ຮອງຮັບ SEO",
    contactHeader: "ຕິດຕໍ່",
    contactText: "ກຳລັງມອງຫາຜູ້ຮ່ວມງານ ຫຼື ມີໂຄງການທີ່ຢາກພັດທະນາບໍ? ສາມາດຕິດຕໍ່ຫາຂ້ອຍໄດ້ເລີຍ. ຂ້ອຍຍິນດີຮ່ວມງານ ແລະ ຊ່ວຍພັດທະນາໂຊລູຊັນທີ່ປອດໄພ, ສ້າງສັນ ແລະ ສ້າງຄຸນຄ່າໄປນຳກັນ!",
    contactEmail: "ສົ່ງຂໍ້ຄວາມ",
    contactGitHubAria: "ໂປຣໄຟລ໌ GitHub",
    contactLinkedInAria: "ໂປຣໄຟລ໌ LinkedIn",
    contactWhatsAppAria: "ຕິດຕໍ່ WhatsApp",
    footerAboutTitle: "UknowTechno ໝາຍຄວາມວ່າຫຍັງ?",
    footerAboutText: "UknowTechno ສະທ້ອນແນວຄິດທີ່ວ່າ ທຸກຄົນສາມາດເຂົ້າໃຈເທັກໂນໂລຢີໄດ້ ຖ້າມີຄວາມຕັ້ງໃຈຮຽນຮູ້ ແລະ ຄົ້ນຄວ້າຢ່າງຕໍ່ເນື່ອງ. ເທັກໂນໂລຢີບໍ່ເຄີຍຢຸດພັດທະນາ ດັ່ງນັ້ນການຮຽນຮູ້ຕະຫຼອດ, ການລອງປະຕິບັດ ແລະ ການຄົ້ນຄວ້າສິ່ງໃໝ່ໆ ຈຶ່ງເປັນກະແຈສຳຄັນໃນການເຕີບໂຕ ແລະ ກ້າວທັນໂລກທີ່ປ່ຽນແປງຢູ່ສະເໝີ.",
    footerTagline: "ສ້າງແອັບ ແລະ ເວັບໄຊແບບຄົບວົງຈອນ — ຈາກໄອເດຍ ຈົນເຖິງນຳໃຊ້ຈິງ.",
    footerProductsTitle: "ຜະລິດຕະພັນ",
    footerLinksTitle: "ລິ້ງດ່ວນ",
    footerConnectTitle: "ເຊື່ອມຕໍ່",
    footerCopyright: "© 2025 UknowTechno. ສະຫງວນລິຂະສິດ.",
    eduHeader: "ປະຫວັດການສຶກສາ",
    edu1Title: "ປະລິນຍາໂທ ວິທະຍາສາດຄອມພິວເຕີ",
    edu1Date: "ມັງກອນ 2023 - ປັດຈຸບັນ",
    edu1Desc: "ຄະນະວິທະຍາສາດທໍາມະຊາດ, ມະຫາວິທະຍາໄລແຫ່ງຊາດລາວ",
    edu2Title: "ປະລິນຍາຕີ ພາສາອັງກິດ",
    edu2Date: "2009 - 2014",
    edu2Desc: "ຄະນະອັກສອນສາດ, ມະຫາວິທະຍາໄລແຫ່ງຊາດລາວ",
    projectsTitle: "ໂຄງການອື່ນໆ",
    interestSports: "ກິລາ",
    chatNewChat: "ແຊັດໃໝ່",
    chatRecent: "ຫຼ້າສຸດ",
    chatToggleSidebar: "ເປີດ/ປິດ ແຖບຂ້າງ",
    chatAIEngine: "UKnowTechno AI",
    chatGreeting: "ມື້ນີ້ມີຫຍັງໃຫ້ຂ້ອຍຊ່ວຍ?",
    chatGreetingSub: "ຂ້ອຍແມ່ນຜູ້ຊ່ວຍ AI ທີ່ຂັບເຄື່ອນດ້ວຍ LLMs ຂັ້ນສູງ.",
    chatInputPlaceholder: "ສົ່ງຂໍ້ຄວາມຫາ AI ຫຼື ວາງຮູບພາບ...",
    chatAttachFile: "ແນບໄຟລ໌ ຫຼື ຮູບພາບ",
    chatUseMic: "ໃຊ້ໄມໂຄຣໂຟນ",
    chatDisclaimer: "AI ອາດມີຂໍ້ຜິດພາດ. ກະລຸນາກວດສອບຂໍ້ມູນສຳຄັນ.",
    chatOffline: "*ລະບົບ AI ກຳລັງປັບປຸງ.*",
    chatTimeout: "*ລະບົບ AI ໃຊ້ເວລາຕອບດົນເກີນໄປ. ອາດຈະອອບໄລນ໌ — ກະລຸນາລອງໃໝ່ອີກຄັ້ງ.*",
    chatRateLimited: "*ທ່ານກຳລັງສົ່ງຂໍ້ຄວາມໄວເກີນໄປ. ກະລຸນາລໍຖ້າ ແລ້ວລອງໃໝ່.*",
    chatSmartOn: "ໂໝດສະຫຼາດ ເປີດ — ກຳລັງໃຊ້ໂມເດວຄລາວຂັ້ນສູງ",
    chatSmartOff: "ໂໝດສະຫຼາດ — ກົດເພື່ອໃຊ້ໂມເດວຂັ້ນສູງສຳລັບຄຳຖາມຍາກ",
    chatListening: "🎤 ກຳລັງຟັງ...",
    adminSystemAdmin: "ລະບົບແອດມິນ",
    adminSecureId: "ໄອດີຄວາມປອດໄພ",
    adminPassphrase: "ລະຫັດຜ່ານ",
    adminInitConnection: "ເຂົ້າສູ່ລະບົບ",
    adminDashboard: "ແຜງຄວບຄຸມ",
    adminAiModels: "ໂມເດວ AI",
    adminKnowledge: "ຖານຂໍ້ມູນ (RAG)",
    adminSignOut: "ອອກຈາກລະບົບ",
    adminSystemOverview: "ພາບລວມລະບົບ",
    adminOnline: "ອອນລາຍ",
    adminPocketbaseStatus: "ສະຖານະ POCKETBASE",
    adminChunks: "ຂໍ້ມູນ",
    adminVectorsQdrant: "ເວັກເຕີໃນ QDRANT",
    adminActiveLlmRoute: "ເສັ້ນທາງ LLM ປັດຈຸບັນ",
    adminAiRouting: "ການຈັດການ AI & ງົບປະມານ",
    adminActiveFree: "ໃຊ້ງານ (ຟຣີ)",
    adminRouteTarget: "ເປົ້າໝາຍ",
    adminTotalUsage: "ການນຳໃຊ້ທັງໝົດ (ບໍ່ຈຳກັດ)",
    adminTokensGenerated: "ໂທເຄັນທີ່ສ້າງ",
    adminMonthlyBudgetLimit: "ງົບປະມານປະຈຳເດືອນ ($)",
    adminCurrentSpend: "ລາຍຈ່າຍປັດຈຸບັນ",
    adminKnowledgeBase: "ຖານຂໍ້ມູນຄວາມຮູ້ (RAG)",
    adminSemanticChunking: "ການຈັດການຂໍ້ມູນ & ຖານຂໍ້ມູນ",
    adminSmartUpload: "ອັບໂຫຼດອັດສະລິຍະ",
    adminAutoPipeline: "ລະບົບຈັດການຂໍ້ມູນອັດຕະໂນມັດ",
    adminUploading: "1. ກຳລັງອັບໂຫຼດເອກະສານ...",
    adminAnalyzing: "2. ກຳລັງວິເຄາະໂຄງສ້າງເອກະສານ...",
    adminApplying: "3. ກຳລັງແບ່ງຂໍ້ມູນ...",
    adminComputing: "4. ກຳລັງສ້າງເວັກເຕີ...",
    adminEditChunk: "ແກ້ໄຂຂໍ້ມູນ",
    adminFileName: "ຊື່ໄຟລ໌",
    adminUnitTopic: "ຫົວຂໍ້ຫຼັກ",
    adminSubTopic: "ຫົວຂໍ້ຍ່ອຍ",
    adminVectorContent: "ເນື້ອຫາຂໍ້ມູນ",
    adminCancel: "ຍົກເລີກ",
    adminCommit: "ບັນທຶກລົງຖານຂໍ້ມູນ",
    adminSearch: "ຄົ້ນຫາເນື້ອຫາ ຫຼື ຫົວຂໍ້...",
    adminHierarchy: "ໂຄງສ້າງ (ໄຟລ໌ > ຫົວຂໍ້)",
    adminVectorPayload: "ເນື້ອຫາ",
    adminActions: "ການຈັດການ",
    adminManual: "ແກ້ໄຂ",
    adminPurge: "ລຶບ",
    adminNoData: "ບໍ່ພົບຂໍ້ມູນ",
    adminUploadDoc: "ອັບໂຫຼດເອກະສານເພື່ອເພີ່ມເຂົ້າຖານຂໍ້ມູນອັດຕະໂນມັດ.",

    // --- Business Home (v2) ---
    navHome: "ໜ້າຫຼັກ",
    navApps: "ແອັບ",
    navServices: "ບໍລິການ",
    navConnect: "ຕິດຕໍ່ສື່ສານ",
    navAboutMe: "ກ່ຽວກັບຂ້ອຍ",
    navHomeAria: "ໄປໜ້າຫຼັກ",
    navAppsAria: "ໄປສ່ວນແອັບ",
    navServicesAria: "ໄປສ່ວນບໍລິການ",
    navConnectAria: "ໄປສ່ວນຕິດຕໍ່ສື່ສານ",
    navAboutMeAria: "ໄປໜ້າກ່ຽວກັບຂ້ອຍ",
    scrollApps: "ແອັບ",
    scrollServices: "ບໍລິການ",
    scrollStack: "ເຄື່ອງມື",
    scrollConnect: "ຕິດຕໍ່",

    bizHeroEyebrow: "ນັກພັດທະນາ Full-Stack · Android & ເວັບ",
    bizHeroHeadline: "ຂ້ອຍສ້າງແອັບ ແລະ ເວັບໄຊ",
    bizHeroHighlight: "ທີ່ຄົນໃຊ້ຈິງ.",
    bizHeroSub: "ປະສົບການ 14+ ປີໃນອຸດສາຫະກຳການທະນາຄານ ແລະ ຊອບແວ ດຽວນີ້ພັດທະນາແອັບ Android ແລະ ຜະລິດຕະພັນເວັບທັນສະໄໝແບບຄົບວົງຈອນ — ຈາກໄອເດຍ ຈົນເຖິງ Play Store ແລະ ນຳໃຊ້ຈິງ.",
    bizHeroCtaApps: "ເບິ່ງແອັບຂອງຂ້ອຍ",
    bizHeroCtaHire: "ປຶກສາໂຄງການຂອງທ່ານ",
    bizHeroStatYears: "14+ ປີປະສົບການ",
    bizHeroStatApps: "4 ແອັບທີ່ສ້າງແລ້ວ",
    bizHeroStatStack: "Full-Stack: Mobile · Web · Backend",

    appsHeader: "ແອັບທີ່ຂ້ອຍໄດ້ສ້າງ",
    appsSub: "ນຳໃຊ້ຈິງເທິງ Play Store, ຢູ່ໃນຂັ້ນຕອນທົດລອງ, ຫຼື ກຳລັງພັດທະນາຢູ່ — ຜະລິດຕະພັນຈິງ ບໍ່ແມ່ນພຽງແຕ່ Demo.",
    statusLive: "ນຳໃຊ້ຈິງເທິງ Play Store",
    statusBeta: "ຂັ້ນຕອນທົດລອງ",
    statusDev: "ກຳລັງພັດທະນາ",
    appCtaInstall: "ເບິ່ງເທິງ Play Store",
    appCtaSoon: "ກຳລັງຈະມາໄວໆນີ້",

    app1Title: "Lao QR Parse: Pay & Budget",
    app1Desc: "ອ່ານລະຫັດ QR ຊຳລະເງິນລາວ ແລະ ປ່ຽນທຸກການສະແກນເປັນການຕິດຕາມງົບປະມານອັດຕະໂນມັດ — ຮູ້ວ່າເງິນຫາຍໄປໃສໂດຍບໍ່ຕ້ອງພິມມືເອງ.",
    app2Title: "OmniKit – Toolkit",
    app2Desc: "ເຄື່ອງມືອານຸກົມ Android ຄົບຊຸດ ລວມເອົາເຄື່ອງມືທີ່ໃຊ້ປະຈຳວັນໄວ້ໃນແອັບດຽວ ສະອາດ ບໍ່ລົບກວນດ້ວຍໂຄສະນາ.",
    app3Title: "Smart HR: Attendance & Leave",
    app3Desc: "ຕິດຕາມການເຂົ້າ-ອອກວຽກ ແລະ ຈັດການການລາພັກ ສຳລັບທີມງານຂະໜາດນ້ອຍ — ລົງເວລາ, ຂໍລາພັກ ແລະ ອະນຸມັດ ໃນຂັ້ນຕອນດຽວ.",
    app4Title: "LinkZap: Easy Food",
    app4Desc: "ແອັບສັ່ງອາຫານທີ່ໄວ ແລະ ງ່າຍ, ປັດຈຸບັນກຳລັງພັດທະນາຢູ່. ຕິດຕາມຊ່ອງທາງໂຊຊຽວມີເດຍຂ້າງລຸ່ມສຳລັບການເປີດຕົວ.",

    servicesHeader: "ສິ່ງທີ່ຂ້ອຍສາມາດສ້າງໃຫ້ທ່ານ",
    servicesSub: "ພັດທະນາແບບຄົບວົງຈອນ — ຂ້ອຍອອກແບບ, ສ້າງ, ທົດສອບ ແລະ ສົ່ງມອບ ບໍ່ແມ່ນພຽງແຕ່ຕົ້ນແບບ.",
    service1Title: "ແອັບມືຖື",
    service1Desc: "ແອັບ Android ພື້ນເມືອງ (Kotlin) ແລະ ຂ້າມແພລດຟອມ (Flutter, React Native, MAUI) — ຈາກແນວຄິດ ຈົນເຖິງການເຜີຍແຜ່ ແລະ ບຳລຸງຮັກສາເທິງ Play Store.",
    service2Title: "ເວັບໄຊ ແລະ ເວັບແອັບ",
    service2Desc: "ເວັບໄຊ ແລະ ເວັບແອັບພລິເຄຊັນທີ່ໄວ, ຮອງຮັບທຸກອຸປະກອນ ດ້ວຍ React, TypeScript, Tailwind, Vue ແລະ Next.js — ສ້າງເພື່ອຜູ້ໃຊ້ຈິງ.",
    service3Title: "Backend ແລະ API",
    service3Desc: "REST API ແລະ ໂຄງລ່າງລະບົບຄລາວທີ່ປອດໄພ ດ້ວຍ Node.js, Supabase, Firebase ແລະ Cloudflare — ຮອງຮັບການເຕີບໂຕຂອງທ່ານ.",
    servicesPricingTitle: "ລາຄາທີ່ສົມເຫດສົມຜົນ",
    servicesPricingText: "ບຸກຄົນ ແລະ ໂຄງການຂະໜາດນ້ອຍ: ຟຣີ. ໂຄງການໃຫຍ່ ຫຼື ທຸລະກິດ: ມາປຶກສາຂອບເຂດ ແລະ ງົບປະມານກັນກ່ອນ — ບໍ່ມີຄ່າໃຊ້ຈ່າຍແບບບໍ່ຄາດຄິດ.",
    servicesCta: "ບອກຂ້ອຍກ່ຽວກັບໂຄງການຂອງທ່ານ",
    service4Title: "ແອັບ ແລະ ເຄື່ອງມື Windows",
    service4Desc: "ເຄື່ອງມືເດັສທັອບ ແລະ ເຄື່ອງມືພາຍໃນສຳລັບ Windows — ສ້າງດ້ວຍ .NET/C#, Python ແລະ Java.",
    service5Title: "ໂມເດວ AI ແລະ ການຄົ້ນຄວ້າ",
    service5Desc: "AI ປະຍຸກ: ລະບົບ RAG, ການຈັດການໂມເດວ LLM ທັ້ງແບບ local ແລະ cloud, ການທົດລອງ fine-tuning ແລະ ຕົ້ນແບບການຄົ້ນຄວ້າ ທີ່ເໜືອກວ່າແຊັດບອດທົ່ວໄປ.",
    service6Title: "ຖານຂໍ້ມູນ ແລະ ເຊີບເວີ",
    service6Desc: "ຊັ້ນຂໍ້ມູນ ແລະ ໂຄງລ່າງພື້ນຖານ: PostgreSQL, MongoDB ແລະ MySQL, ພ້ອມການບໍລິຫານເຊີບເວີ Linux ແລະ Docker.",

    stackHeader: "ເຄື່ອງມື ແລະ ເທັກໂນໂລຢີທີ່ໃຊ້",
    stackSub: "ພາສາ, ເຟຣມເວີກ ແລະ ໂຄງລ່າງພື້ນຖານທີ່ຢູ່ເບື້ອງຫຼັງທຸກຜົນງານ.",
    stackCtaText: "ຢາກເບິ່ງລາຍການເຕັມ? ເບິ່ງຄັງເຕັກໂນໂລຢີທັງໝົດຢູ່ໜ້າກ່ຽວກັບຂ້ອຍ.",
    stackCtaLink: "ເບິ່ງເຕັກໂນໂລຢີທັງໝົດ →",

    connectHeader: "ຕິດຕາມ ແລະ ຕິດຕໍ່ຫາຂ້ອຍ",
    connectSub: "ຜົນງານໃໝ່, ບັນທຶກການພັດທະນາ ແລະ ການເປີດຕົວ — ກ່ອນຂຶ້ນ Play Store.",
    connectYouTubeDesc: "ວິດີໂອບັນທຶກການພັດທະນາ ແລະ ນຳສະເໜີແອັບ",
    connectGitHubDesc: "ໂຄ້ດແບບເປີດ, ການທົດລອງ ແລະ ໂຄງການສ່ວນຕົວ",
    connectFacebookDesc: "ຂ່າວສານ, ການປະກາດ ແລະ ເບື້ອງຫຼັງການເຮັດວຽກ",
    connectPlayStoreDesc: "ແອັບທັງໝົດທີ່ເຜີຍແຜ່ໄວ້ບ່ອນດຽວ",
    connectFacebookAria: "ໜ້າ Facebook",
    connectTikTokDesc: "ວິດີໂອສັ້ນ, ນຳສະເໜີແອັບ ແລະ ເບື້ອງຫຼັງການພັດທະນາ",
    connectTikTokAria: "ໂປຣໄຟລ໌ TikTok",

    homeAboutTeaser: "ຢາກຮູ້ເລື່ອງລາວທັງໝົດ — 14 ປີໃນທະນາຄານ, ປະລິນຍາໂທ Computer Science ແລະ ເສັ້ນທາງມາຮອດຈຸດນີ້?",
    homeAboutTeaserCta: "ອ່ານເລື່ອງລາວຂອງຂ້ອຍ →"
  }
};

type LanguageContextType = {
  language: Language;
  toggleLanguage: () => void;
  t: (key: keyof typeof translations.en) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'lo' : 'en'));
  };

  const t = (key: keyof typeof translations.en) => {
    return (translations[language] as any)[key] || translations.en[key];
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
